# monitor.py

import os
import json
from datetime import datetime
from pydantic import BaseModel
from a2a.a2a_protocol import BUS

# Ensure directories exist
os.makedirs("output", exist_ok=True)
os.makedirs("output/logs", exist_ok=True)

LOG_FILE = "output/logs/run.log"
FINAL_JSON = "output/final.json"
FINAL_MD = "output/final.md"


def log(msg: str):
    ts = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    line = f"{ts} {msg}"

    print(line)

    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(line + "\n")


# ---------- Pydantic Structured Output ----------
class FinalOutput(BaseModel):
    ticket_id: str
    troubleshoot: dict
    escalation: dict
    timestamp: str


# ---------- MONITOR LOOP ----------
def monitor_loop():
    BUS.register("monitor_agent")
    log("Monitor Agent started. Waiting for messages...")

    while True:
        msg = BUS.receive("monitor_agent", timeout=1)
        if not msg:
            continue

        if msg.type != "final_decision":
            continue

        payload = msg.payload
        ticket_id = payload["ticket_id"]

        log(f"Monitor received final decision for ticket {ticket_id}")

        # Build structured output
        final = FinalOutput(
            ticket_id=ticket_id,
            troubleshoot=payload["troubleshoot"],
            escalation=payload["escalation"],
            timestamp=datetime.now().isoformat()
        )

        # ---------- Save JSON ----------
        with open(FINAL_JSON, "w", encoding="utf-8") as f:
            f.write(final.model_dump_json(indent=4))

        log(f"Saved JSON → {FINAL_JSON}")

        # ---------- Create Markdown Safely ----------
        md_lines = [
            "# 📝 Final Support Report",
            f"**Ticket ID:** {final.ticket_id}",
            f"**Generated At:** {final.timestamp}",
            "",
            "---",
            "",
            "## 🛠 Troubleshooting Results",
            "```json",
            json.dumps(final.troubleshoot, indent=4),
            "```",
            "",
            "## 📊 Escalation Decision",
            "```json",
            json.dumps(final.escalation, indent=4),
            "```",
            "",
            "---",
            "Generated by **AI-Powered Multi-Agent Helpdesk System**."
        ]

        md_content = "\n".join(md_lines)

        with open(FINAL_MD, "w", encoding="utf-8") as f:
            f.write(md_content)

        log(f"Saved Markdown → {FINAL_MD}")
        log("=== END OF WORKFLOW ===\n")
